### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by HeadWord** [msniveau/discord-statusbotv2#4]
Anytime i try to add a server i get this error and it crashes the bot. 

```2019/09/18 22:41:49 Starting monitoring goroutine.
2019/09/18 22:41:50 Bot is now running.  Press CTRL-C to exit.
2019/09/18 22:42:17 Starting command handler: addserver
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x6095b9]

goroutine 52 [running]:
discord-statusbot/lib/queryli.Query.func1(0x0)
        /home/nibastian/IdeaProjects/discord-statusbot/lib/queryli/queryli.go:50 +0x19
panic(0x71b440, 0xa06060)
        /usr/lib/golang/src/runtime/panic.go:513 +0x164
discord-statusbot/lib/queryli.Query(0x11813516, 0x3, 0x1181351a, 0x13, 0x63dd, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/nibastian/IdeaProjects/discord-statusbot/lib/queryli/queryli.go:52 +0xdd
discord-statusbot/lib/commands.AddServerCommand(0x11802300, 0x1194dc60, 0x11802300, 0x11c08f90, 0x5, 0x5)
        /home/nibastian/IdeaProjects/discord-statusbot/lib/commands/commands.go:65 +0x1bd
main.reader.func1(0x118c4000, 0x9dea41, 0x1)
        /home/nibastian/IdeaProjects/discord-statusbot/cmd/main.go:46 +0x405
created by main.reader
        /home/nibastian/IdeaProjects/discord-statusbot/cmd/main.go:33 +0xb9```

**Comment by HeadWord** [comment]
I believe the issue is resolved. It just started working after a restart.
